---
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-mock

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: k8s-mock
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        service: server
        app: server
    spec:
      containers:
        - ports:
            - containerPort: 3000
          image: localhost:32000/k8s-mock
          name: server
          resources: {}
          securityContext:
            capabilities:
              drop:
                - ALL
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: k8s-mock
  labels:
    app: server
spec:
  ports:
    # Receiver port
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    service: server
